# NUMPY

In [ ]:
distance = [45,80,9]
speed = [5,10,3]
time = distance/speed
print(time)

# if we will run this statement nothing will happen instead we will get bunch of error, because it is a collection of element or we can say it is a list, if we really want to make sense of this statement we have to use "for" loop, instead of "for" loop we can also use NUMPY.

In [2]:
import numpy as np

In [3]:
# overcome the prior challenge using

dist = np.array(distance)
spd = np.array(speed)
time = dist/speed
print(time)
len(time)

[9. 8. 3.]


3

In [4]:
type(time)

# now we can check the type

numpy.ndarray

### why numpy array is useful?

#### Numpy data structure like array are pre compiled data type, if we create a numpy array, any operation we write on them they will apply on all the element really fast. Numpy operations are 10 to 100 times faster than normal list operations. Numpy operations are as faster as FORTRAN operations. if we create an array they have pre build functions and data types for an array.

In [5]:
# some examples

a = [1,2,3,4,5]
b = [6,7,8,9,10]
print(a+b)

# we wanted to add the element but it actually concatenated.
# to solve this problem....

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


#### np.array

In [6]:
x = np.array([1,2,3,4,5])
y = np.array([6,7,8,9,10])
print(x+y)


# but if we will try to add elements with different dimension like x has 5 element and y has 4 elements then this will throw an error because if we will manually create an array its dimension should be same.


[ 7  9 11 13 15]


In [7]:
# can also do something like this..
x**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [8]:
# but what if we will add string or other data type elements as a new element in the numpy array means other than numeric value?

c = np.array((1,3,4,"xyz"))
c

# object(string)
#       |
#    float
#      |
#    integer

# if there will be combination of int & float elements they automatically shift as float type, if combination of int & string it will automaticaly shift in object or string type and so on.
    

array(['1', '3', '4', 'xyz'], dtype='<U11')

#### np.arange

In [9]:
g = np.arange(10)
g

# generate a range of number.. 10 numbers means 0 to 9.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
s = np.arange(5,51,2) 
s
# here 5 is starting point, 51 is the last one and 2 is the step function.
# range goes from starting till (last-1). last element is omitted.

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])

#### np.linspace

In [11]:
lnsp = np.linspace(30,100,5)
lnsp

# first element will be 30, last will be 100, and there will be 5 equidistand number.
# formula..
# (100-30)/(5-1) = 70/4 = 17.5, d/f b/w each number like 30+17.5 = 47.5 and so on..

array([ 30. ,  47.5,  65. ,  82.5, 100. ])

In [12]:
# can also do..

z = np.linspace(1,10,30)
z

#(10-1)/(30-1) = 0.3103448275862069

array([ 1.        ,  1.31034483,  1.62068966,  1.93103448,  2.24137931,
        2.55172414,  2.86206897,  3.17241379,  3.48275862,  3.79310345,
        4.10344828,  4.4137931 ,  4.72413793,  5.03448276,  5.34482759,
        5.65517241,  5.96551724,  6.27586207,  6.5862069 ,  6.89655172,
        7.20689655,  7.51724138,  7.82758621,  8.13793103,  8.44827586,
        8.75862069,  9.06896552,  9.37931034,  9.68965517, 10.        ])

## Dimensions

#### 0 dimension                                ->   dot(.)
#### 1 dimension                                ->   array
#### 2 or more dimensions                ->   matrix


In [13]:
# 2 DIMENSIONS 

data = np.array((2,30,45,6,3,22,13,41,5))              # creating numpy array
data = data.reshape(3,3)                               # converting numpy array into 3*3 matrix
data

array([[ 2, 30, 45],
       [ 6,  3, 22],
       [13, 41,  5]])

In [14]:
# 3 DIMENSIONS 

data1 = np.array((1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18))
data1 = data1.reshape(3,3,2)                                     # converting into 3*3*2 matrix
data1

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])

In [15]:
# 4 DIMENSIONS

data1 = data1.reshape(3,3,2,1)       # converting into 3*3*2*1
data1

array([[[[ 1],
         [ 2]],

        [[ 3],
         [ 4]],

        [[ 5],
         [ 6]]],


       [[[ 7],
         [ 8]],

        [[ 9],
         [10]],

        [[11],
         [12]]],


       [[[13],
         [14]],

        [[15],
         [16]],

        [[17],
         [18]]]])

In [16]:
# can also do..

even_data = (data1 % 2 == 0)
even_data

array([[[[False],
         [ True]],

        [[False],
         [ True]],

        [[False],
         [ True]]],


       [[[False],
         [ True]],

        [[False],
         [ True]],

        [[False],
         [ True]]],


       [[[False],
         [ True]],

        [[False],
         [ True]],

        [[False],
         [ True]]]])

In [17]:
# if want to get the original values..

data1[even_data]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

#### np.zeros

In [18]:
# to print 50 zeros

np.zeros(50)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
# to print 5's in a 4*4 matrix

np.zeros((4,4))+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

#### np.ones

In [20]:
# to print ones in a 4*5 matrix

np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

#### np.eye

In [21]:
# identity matrix

# if we flip the rows or column the matrix will remain same

np.eye(3)



array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
np.eye(5,6)    # it will create a 5*6 matrix but no more remain as identity matrix

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

#### np.diag

In [23]:
# populate the diagonal elements only

np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])